### ISSUE TITLE
Problems with the old production tool

### ISSUE THREAD

**Issue by VictorBarbosaMartins** [gammasim/simtools#660]
Hello. I am listing here six problems that I have found with the old production tool `production.py`. I already looked in some of these, but before spending more time on them, I would like to raise a discussion whether this is necessary. @orelgueta  suggests using his new production tool `simulate_prod.py` and discontinue this old tool. However, the new tool is not yet able to simulate corsika alone. Given that I am moving my focus away from corsika and I am concentrating more on the simtel histograms, at the moment the corsika output is indeed not needed. The problem is that we need to have a tool to simulate corsika alone, otherwise the entire corsika output (corsika histograms) module does not make sense and we would not be able to compare the results of different corsika versions. Should we fix the issues mentioned below? Should we discontinue `production.py`? Should we implement corsika simulation within `simulate_prod.py`? Please share your thoughts.

### **Problems with the production tool**
- [x] print function not used anywhere:
https://github.com/gammasim/simtools/blob/5d966190935786cba19836dc2c2d1652a17336fe/simtools/simulator.py#L596-L622
- [ ] No error message (neither printed nor passed to .err log file) when running the production with `--array-only` in case no corsika simulation was done before (to reproduce it yourself, create the directory and try ```simtools-production --productionconfig ./tests/resources/prod_config_test.yml --task simulate --array_only --submit_command local --data_directory test_sim_telarray/ --output_path test_sim_telarray/```). When running manually the bash script generated by simtools, the error is printed out. This error should go to the log file:
```
Input file: /workdir/external/simtools/test_sim_telarray/corsika-data/North/gamma/data/run000002/corsika_run000002_gamma_za020deg_azm000deg_North_TestLayout_test-production.zst
/workdir/external/simtools/test_sim_telarray/corsika-data/North/gamma/data/run000002/corsika_run000002_gamma_za020deg_azm000deg_North_TestLayout_test-production.zst: No such file or directory
No (or only empty) input files have been processed.
```
- [ ] Simulating with the same run number leads to an error, which is expected (to reproduce, try yourself twice in a row ```simtools-production --productionconfig ./tests/resources/prod_config_test.yml --task simulate --showers_only --submit_command local --data_directory test_sim_telarray/ --output_path test_sim_telarray/``` and check the log file ```cat /workdir/external/simtools/test_sim_telarray/simtools-output/test-production/corsika/logs/log_sub_corsika_run000001_gamma_North_TestLayout_test-production.err```). However, neither in the print out message nor in the error log file we get which file is meant by that (and its location):
```
Runtime error - See below the relevant part of the log/err file.

/workdir/external/simtools/test_sim_telarray/simtools-output/test-production/corsika/logs/log_sub_corsika_run000001_gamma_North_TestLayout_test-production.err
====================================================================

run000001: File exists

====================================================================

ERROR::job_manager(l130)::_submit_local::

Runtime error - See below the relevant part of the log/err file.

/workdir/external/simtools/test_sim_telarray/corsika-data/North/gamma/log/log_corsika_run000001_gamma_North_TestLayout_test-production.log.gz
====================================================================



====================================================================
```
- [ ] Production tool (simtel) not simulating according to expected. No print out message, nor error in the log file is given. To reproduce this, run ```simtools-production --productionconfig ./tests/resources/prod_config_test.yml --task simulate --showers_only --submit_command local --data_directory test_sim_telarray/ --output_path test_sim_telarray/``` first and then ```simtools-production --productionconfig ./tests/resources/prod_config_test.yml --task simulate --array_only --submit_command local --data_directory test_sim_telarray/ --output_path test_sim_telarray/```. This is already pointed out here #644. Suggestion: do not wait until the end of the script to compact the log files, but save them on the fly.
- [x] (Addressed in [723](https://github.com/gammasim/simtools/pull/723) related to the previous issue, the production tool is not working, likely due the fact that the simtel part is searching for the wrong file corsika output file name. A zero padding seems to be missing somewhere, as pointed out here: https://github.com/gammasim/simtools/issues/646#issuecomment-1785557714
- [x] As pointed out in #645, simtel "temporary files" are saved locally and are not deleted after running the script.

**Comment by GernotMaier** [comment]
@VictorBarbosaMartins - I am removing the production.py application. I realize that a lot of issue I have with the production configuration files is that production.py and simulate_prod.py are using similar, but different configurations. Also both tools are almost exactly the same.

Could you provide me with input on what functionality production.py has and not simulate_prod.py? Best with input / configuration files and/or examples?

**Comment by VictorBarbosaMartins** [comment]
Hi @GernotMaier. I still have the same opinion that we should not delete it as long as we don't have all the functionalities implemented in the new tool. Two things are not implemented in the new tool:

- T be able to save the CORSIKA output file from a simulation using simtel_array;
- To simulate only the CORSIKA part and save its output without piping it into simtel_array.

Raul implemented the old tool and Orel the new one, so it would cost me some time If I am to implement these two points. If you want to go ahead with this idea, I suggest you try to implement these two points or alternatively I can address this after we are finished with the trigger rate tool. But I do not agree to simply remove the old tool at the moment. These two functionalities in the new tool are the only means we have to produce CORSIKA output files in simtools. Without this option the entire CORSIKA histogram module (+ CORSIKA visualization) and application will be useless.

**Comment by GernotMaier** [comment]
Adding corsika will be very easy. Can you give me an example how it is used? Is making sure that corsika runs and the log files look good is reasonable enough or does the production.py does something with the output.

**Comment by VictorBarbosaMartins** [comment]
You can use as in the integration test:
```
simtools-production --config tests/integration_tests/config/production_showers_only.yml
```

And yes, testing whether the output `zst` file and the log files are produced is enough to assure the tool is working.

**Comment by GernotMaier** [comment]
PR #910 addresses this issue:

- add possibility to run corsika with simulate_prod (use `--simulator corsika`)
- removes production.py
